backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: 'feed'
    label: 'Feed'
    label_singular: 'Post'
    folder: 'content/feed'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Body', name: 'body', widget: 'string' }
      - { label: 'Avatar', name: 'avatar', widget: 'image' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Post Color', name: 'postColor', widget: 'color', default: '#0000ff'}
      - { label: 'Tect Color', name: 'textColor', widget: 'color', default: '#ffffff'}



